//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public int ActivityID { get; set; }
        public int EventID { get; set; }
        public System.DateTime ActivityDateStart { get; set; }
        public int ActivityDaysCount { get; set; }
        public string ActivityName { get; set; }
        public int ActivityDay { get; set; }
        public string ActivityTimeStart { get; set; }
        public int ModeratorID { get; set; }
        public Nullable<int> JuryID1 { get; set; }
        public Nullable<int> JuryID2 { get; set; }
        public Nullable<int> JuryID3 { get; set; }
        public Nullable<int> JuryID4 { get; set; }
        public Nullable<int> JuryID5 { get; set; }
        public Nullable<int> WinnerID { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
    }
}
