//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moderators()
        {
            this.Activities = new HashSet<Activities>();
        }
    
        public int ModeratorID { get; set; }
        public string ModeratorFIO { get; set; }
        public string GenderCode { get; set; }
        public string Email { get; set; }
        public System.DateTime ModeratorBirthday { get; set; }
        public int CountryID { get; set; }
        public string ModeratorPhone { get; set; }
        public int DirectionID { get; set; }
        public int EventID { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Directions Directions { get; set; }
        public virtual Events Events { get; set; }
        public virtual Genders Genders { get; set; }
    }
}
