//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizers
    {
        public int OrganizerID { get; set; }
        public string OrganizerFIO { get; set; }
        public string Email { get; set; }
        public System.DateTime OrganizerBirthday { get; set; }
        public int CountryID { get; set; }
        public string OrganizerPhone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public string GenderCode { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Genders Genders { get; set; }
    }
}
